### ISSUE TITLE
[BUG] v1.4.18 Cannot save new snippet PHP 8

### ISSUE THREAD

**Issue by BBloke** [evocms-community/evolution#103]
Cannot save a new Snippet. Click any action button sets an error in browser console.

![image](https://user-images.githubusercontent.com/24464015/172346910-f9d563c8-e5e5-4d9d-8484-f2d726a2aa0b.png)

Saving existing Snippets works ok.

Click Add Snippet Variable
Give it a name.
Click Save (nothing happens)
It doesn't matter how many fields are completed
Cancel button does nothing too.

**Comment by bossloper** [comment]
I cannot reproduce these errors on 1.4.18 (upgraded existing site)

What PHP version is this exactly?
I tried setting Detection level of PHP errors to All and still no errors.
Has anyone else confirmed them yet?

**Comment by BBloke** [comment]
My NAS is running 8.0.17

I've fixed the bug that I found which related to undefined array key issue. 

The bug was because the js code wasn't fully complete and the warning was hidden in the page script. 

When a page is blank nothing is in the content variable so no keys are viable!

Check out my pull request #104

**Comment by bossloper** [comment]
Thanks. So this specific save error was your setup only, bad js file?

Yes, I am looking at the #104 changes. Trouble is I cannot get the system to show errors that need fixing :-)

e.g. https://github.com/evocms-community/evolution/pull/104/commits/b466055a1ae6a1e12391b8bc8c0e42c01c3b51a4
I cannot get any errors when creating a snippet, even with all fields left blank so just wondering if my setup is out of the ordinary (php 8.0.19) or what is going on.

Update - ok I see these now as PHP Warnings.

**Comment by BBloke** [comment]
I have suspected my NAS install of PHP but when I clicked create new snippet nothing happened. JS didn't fire.

I checked the html on the page and there were warning messages relating to array keys. 

One line was to produce a URL which had id= $_REQUEST['id']. As it wasn't set it threw a warning so the JS code was:

Index.php?id=warning: undefined array key "id"....

Changing it as I did allowed the page to save as required.

There were also warnings in the fields of the same nature when the form was blank.

**Comment by BBloke** [comment]
I will investigate on my laptop which is PHP 8.1 and let you know.

The main issue I have is I cannot control which version my NAS uses and changing my laptop installation is tedious. I fell out with lamp and xampp as I've found them just as unreliable on windows so reluctant to use them on Linux.

**Phew I'm happy and thankful you can see the warnings **

**Comment by Pathologic** [comment]
I cannot reproduce this, PHP 8.1.6.

**Comment by Pathologic** [comment]
Ok, I had display_errors parameter switched off.

**Comment by BBloke** [comment]
I have my php 8 the same as php 7.  Display errors are on.  There were never any warnings on 7.  They've only shown in 8.

Should it be off?

**Comment by Pathologic** [comment]
I have it switched off by default.

9 июня 2022 г. 10:44:00 GMT+03:00, BBloke ***@***.***> пишет:

**Comment by bossloper** [comment]
I have it set as 'Ignore warnings of a slight notice level' on a production site.
But it makes sense for development to see a few more of the minor 'non-breaking' notices to help clean the code up and make it more ready for future PHP versions when these warnings might become errors.

**Comment by Pathologic** [comment]
Hope I've fixed all these errors: https://github.com/evocms-community/evolution/commit/0489e20d5e5aaef5acbeaf1fbfc6e579990c3e75
https://github.com/evocms-community/evolution/commit/3e80cac1aa8ab48779b3f98f51e3b00356ff21dc
