### ISSUE TITLE
[BUG] v3 PHP 8 Clicking Manage Images from TreeElement shows page but with unknown error

### ISSUE THREAD

**Issue by BBloke** [evocms-community/evolution#107]
In v3.1.12 Clicking the Manage Images icon at the top of the element tree displays the page but has unknown error shown.

![image](https://user-images.githubusercontent.com/24464015/172653770-dd38df3e-8070-493c-83fa-0f0faff8efff.png)

**Comment by Pathologic** [comment]
There's something wrong with your server settings or folder access permissions. See browser console or server error log to find out.

**Comment by BBloke** [comment]
This is the event log error in short

Error : imagecreatefrompng(): gd-png: libpng warning: iCCP: known incorrect sRGB profile

**Comment by Pathologic** [comment]
So, one of your images has incorrect sRGB profile. Send it to me to check.

**Comment by BBloke** [comment]
It's the logo image in assets/images.

I've just deleted and redownloaded the image from github and same thing.

No images in folder.  No error.
I've tried it with a different image and I get the same error. 

I'll look into it.  Could be my php.

**Comment by BBloke** [comment]
Trying the same in v1.4.18 is without issue.  Very strange. I've read this is a libpng issue.  The code has @ so it should be suppressed but isn't (not an Evo issue).

libpng version is 1.6.37 in php 8.0.17.

There looks to be a little more going on with v3 over v1.4. I can see this url gives server 500 error:

```
manager/media/browser/mcpuk/browse.php?type=images&lng=en&act=init
```

its an ajax call.  Also, this url is getting sent in the script code of the page but I'm having diffculty finding where it's coming from.

```
manager/media/browser/mcpuk/browse.phpmedia/browser/mcpuk/browse.php?filemanager=media/browser/mcpuk/browse.php&type=images
```

**Comment by Pathologic** [comment]
Open developer tools and see network tab.

**Comment by BBloke** [comment]
@Pathologic Yeah, I've got that bit but I couldn't find where in the code is was getting generated from.  Granted, I haven't much time to look into but I'm sure I'll find it soon.

The browser.php file across both versions are identical. 

More when I get home as I can run a better comparison.
