### ISSUE TITLE
добавить событие OnLoadSettings

### ISSUE THREAD

**Issue by autogen-travel** [evocms-community/evolution#109]
### Описание
Добавить новое событие OnLoadSettings

### Зачем это нужно?
Иметь возможность изменять $modx->config

### Предлагаемое решение
в document.parser добавить в метод getSettings 
`$evtOut = $this->invokeEvent('OnLoadSettings', array('config' => $this->config));
  if (is_array($evtOut) && count($evtOut) > 0) {
      $this->config = unserialize(array_pop($evtOut));
  }`
И само событие в БД

**Comment by Pathologic** [comment]
```
$this->invokeEvent('OnLoadSettings', ['config' => &$this->config]);
```

**Comment by Pathologic** [comment]
1.4.x:
https://github.com/evocms-community/evolution/commit/3ab6a1c2e328bbcd58ae1defb1d464cb5e75cfed
https://github.com/evocms-community/evolution/commit/8dd99f17f69037f05c9fd08f31352ce1014f25dc
3.x:
https://github.com/evocms-community/evolution/commit/070d6c9ff665c4029bff87d085053a6a9e13388e
