### ISSUE TITLE
[BUG] 1.4.18 viewing frontend pages with tvs using @INHERIT

### ISSUE THREAD

**Issue by bossloper** [evocms-community/evolution#111]
Errors is viewing pages that have an unpublished or protected (webuser permission) parent page

Seems to be a page that has a template with TV that uses @INHERIT in default field for example
Preview a page that is a child of an unpublished page gives an error

![Untitled1](https://user-images.githubusercontent.com/1744687/173020551-82eb30c6-9533-40d0-8e65-cd6685a3d99c.png)
![Untitled](https://user-images.githubusercontent.com/1744687/173020566-471c360d-3b78-4cd4-8d8c-e10e95977e38.png)

I think maybe a getTemplateVars issue? But not sure.

Works with php7.4

EvoCMS version: 1.4.18
PHP version: 8.1.6

**Comment by Pathologic** [comment]
The problem is more complex. We can add an option to ignore document permissions:
https://github.com/evocms-community/evolution/pull/112
But is it correct to get values from protected documents?

If not, then there's a problem of caching: user with permissions sees parameter value, then page is cached, then everybody sees parameter value.

**Comment by bossloper** [comment]
For compatibility it should work in same logic as it does with php 7.4, just no error.
It does also error (for php8.x) on documents that are not protected too, just unpublished.

**Comment by bossloper** [comment]
It very nearly all works.
I still get an error if the resource is a child (not a top level resource) of a resource using a different template that does not contain the same tv as the child.
![173020566-471c360d-3b78-4cd4-8d8c-e10e95977e38](https://user-images.githubusercontent.com/1744687/173079355-e510ad07-9d12-44e7-b190-5596da098a41.png)

**Comment by Pathologic** [comment]
> For compatibility it should work in same logic as it does with php 7.4, just no error. It does also error (for php8.x) on documents that are not protected too, just unpublished.

So we cannot receive values from protected documents, but what about cache.

**Comment by Pathologic** [comment]
Another case:
```
Doc 1 (public) - value=123
    Doc 2 (protected)
        Doc 3 (public) - value=@INHERIT
```
What value should we get for Doc 3?

**Comment by bossloper** [comment]
Tricky! Not sure there is a right or wrong answer and depending on the situation you might want it to work differently.
I suppose right now, again for current compatibility, it should work as it does now for php7.4 otherwise it may break expected logic for some installs?

**Comment by Pathologic** [comment]
I'm not sure too. It's rather strange situation, when public resource has protected parent.

**Comment by Pathologic** [comment]
https://github.com/evocms-community/evolution/pull/112
