### ISSUE TITLE
[BUG] v1.4 PHP 8.1 FileSource issues related to snippets

### ISSUE THREAD

**Issue by BBloke** [evocms-community/evolution#118]
This is a fresh installation of Evo 1.4 CE from the latest github code.

All snippets are installed with a file source.  I understand this pulls the code from the file and inserts it in the snippet content box which is then saved to the database.

Whilst trying to bring my work site upto php 8.1 I found the following issue with filesource and working with snippets.

**Creating a new snippet**
1. Create a new snippet (test)
2. Saved ok
3. Add the following as a static file source: test/test.snippet.php
4. Static file path is not saved, file not created.

**Existing snippet with static file source (no physical directory or file exists). **
1. Open existing snippet
2. Change snippet content
3. Give it a static file 'test/test.snippet.php'
4. Content is saved but no file created.

Should a file be created?

**Existing snippet with existing file source. **
1. Open existing snippet
2. Change snippet content
3. Give it a static file 'test/test.snippet.php'
4. Content is saved to file.

**Comment by Pathologic** [comment]
Should a file be created? - no.
