### ISSUE TITLE
[BUG] v1.4 PHP 8.1 upgrading existing site doesn't update .tpl files in install folder.

### ISSUE THREAD

**Issue by BBloke** [evocms-community/evolution#120]
I have an old site running 1.4.18 CE.  

1. Download latest github files
2. Copy over existing files.
3. run /install
4. No snippets are updated ( i haven't checked anything else)

I checked "if".

Before the update the snippet had the full PHP code.
After the install the snippet still had the full PHP code whereas the install folder has the code:

```php
//<?php
/**
 * if
 * 
 * A simple conditional snippet. Allows for eq/neq/lt/gt/etc logic within templates, resources, chunks, etc.
 *
 * @category 	snippet
 * @version 	1.3
 * @license 	http://www.gnu.org/copyleft/gpl.html GNU Public License (GPL)
 * @internal	@properties 
 * @internal	@modx_category Navigation
 * @internal    @installset base, sample
 * @author  	Created By Bumkaka (bumkaka@yandex.ru)
 */
 
return require MODX_BASE_PATH.'assets/snippets/if/snippet.if.php';
```

**Comment by Pathologic** [comment]
Because of filesource plugin

**Comment by BBloke** [comment]
Does that mean that an updated site must manually do any snippet changes too?

Do you think it would be a good idea to move away from using static files in snippets etc on a default installation?

**Comment by Pathologic** [comment]
If you disable FileSource plugin, you'll see the same contents as in tpl files from install folder.
