### ISSUE TITLE
3.1.12 Cannot save manager language in configuration

### ISSUE THREAD

**Issue by cimt** [evocms-community/evolution#125]
Cannot save manager language in configuration.
It is always displayed in English! ...no matter which language you select.

Evolution CE 3.1.12
PHP 8.0

**Comment by Pathologic** [comment]
I cannot reproduce.

**Comment by cimt** [comment]
Hello,

When selecting DE or NL, the **System configuration tabs** all in English.

when I select RU it works...   ;-)

**Comment by Pathologic** [comment]
![image](https://user-images.githubusercontent.com/3012304/174568214-d9504180-741b-4d8c-9622-a9bc4aadf601.png)

**Comment by cimt** [comment]
found the error...

in core > lang > de > global.php ...line16

NOT: $modx_lang_attribute = 'en';
MUST: $modx_lang_attribute = 'de';

I think with **NL**, the same problem!
