### ISSUE TITLE
CE 1.4.19: warning after click new resource

### ISSUE THREAD

**Issue by cimt** [evocms-community/evolution#130]
when you click on **"new resource"** the following warning is displayed: 

- Warning: Undefined array key "type" in D:\...\assets\plugins\codemirror\codemirror.plugin.php on line 101
- Warning: Undefined array key "pagetitle" in D:\...\assets\plugins\codemirror\codemirror.plugin.php on line 105
- Warning: Undefined array key "id" in D:\...\assets\plugins\codemirror\codemirror.plugin.php on line 107

Evolution CE 1.4.19
PHP 8.0

**Comment by Pathologic** [comment]
Failed to reproduce.
