### ISSUE TITLE
v3.x Composer dependencies require PHP 8.1+

### ISSUE THREAD

**Issue by BBloke** [evocms-community/evolution#135]
Installing current v3 code requires server to be on PHP 8.1.  

As my servers are running v8.0 and v7.4 the site now breaks including manager.

**Comment by BBloke** [comment]
To get around it I've run composer update and certain packages were downgraded on both php8 and php7.4 servers

**Comment by Pathologic** [comment]
https://github.com/evocms-community/evolution/commit/84f94e57d809e58b763406c3668369a2b6f90723
