### ISSUE TITLE
Uncaught SyntaxError: '' string literal contains an unescaped line break

### ISSUE THREAD

**Issue by cimt** [evocms-community/evolution#139]
Last dev Version 1.4.19
@Pathologic
after your last changes i get this **js error in Manager** after saving a document:
Uncaught SyntaxError: '' string literal contains an unescaped line break

**Comment by Pathologic** [comment]
https://github.com/evocms-community/evolution/commit/d06614e808cadf21def6ef302559b6675d446f2d
