### ISSUE TITLE
[BUG] InstalledVersions.php: failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by 0test** [evocms-community/evolution#142]
### Описание 
Обновлял через консоль с 3.1.11 до 3.1.12 

![image](https://user-images.githubusercontent.com/10080727/178220000-7ac4ee53-2434-4320-b727-56b9508fa809.png)

### Как воспроизвести
```
cd core
composer update
php artisan make:site update
```

После сделал composer update заново и всё ожило. Однако бага была, мб пригодится.
### Окружение
Версия EvoCMS:  3.1.11
Версия PHP: 7,4
Версия MySQL: 10.6.7-MariaDB-log - mariadb.org binary distribution
Другая информация: Openserver

**Comment by leonie12** [comment]
Same here, but update seems to work nonetheless.
