### ISSUE TITLE
Warning: Undefined array key "alias" EVO or PageBuilder error?

### ISSUE THREAD

**Issue by cimt** [evocms-community/evolution#145]
Evolution CE 3.1.12 clean install / PHP 8.0 
**PageBuilder works without error**

Evolution CE 1.4.20 clean install / PHP 8.0 
**PageBuilder doesn't work**

**Does EVO 1.4.20 produce the error?** ...

Warning: Undefined array key "alias" in ...\assets\plugins\pagebuilder\tpl\form.tpl on line 32
...\assets\plugins\pagebuilder\tpl\container.tpl on line 5
...\assets\plugins\pagebuilder\tpl\container.tpl on line 11 " data-formid="94a382eab4678fd1bbc02f5c6b08f7dc">

Browser Console
Uncaught SyntaxError: '' string literal contains an unescaped line break manager:1241:55
Uncaught SyntaxError: expected expression, got '<' manager:1317:11

**Comment by Pathologic** [comment]
It's PageBuilder error.
