### ISSUE TITLE
Configuration still says „MODX Configuration“

### ISSUE THREAD

**Issue by leonie12** [evocms-community/evolution#149]
### Expected behavior
Should be „EvoCMS Configuration“ or similar

### Environment
EvoCMS version: Evo CE 3.1.12

**Comment by Pathologic** [comment]
Where is it?

**Comment by leonie12** [comment]
The main headline in the settings tab. At least in german translation.

**Comment by leonie12** [comment]
There are some more occurences of MODx/modx in the lang files under core/lang/ .
Also the link to the forums (http://forums.modx.com) over there seems outdated.

**Comment by fourroses666** [comment]
https://www.transifex.com/evo-cms-community/

**Comment by Pathologic** [comment]
Fixed at transifex
