### ISSUE TITLE
[BUG] Нельзя зайти на страницу защищенного ресурса

### ISSUE THREAD

**Issue by mTresk** [evocms-community/evolution#15]
### Описание 
Если сделать ресурс принадлежащим к какой-либо группе, то при попытке зайти на url этого ресурса идет редирект на главную.

### Как воспроизвести
Если еще нет, то создаем группу пользователей, группу ресурсов, связываем их. В ресурсе в правах доступа выбираем созданную группу. Разлогиниваемся и пробуем зайти на этот ресурс.

### Окружение
Версия EvoCMS: 3.1.9
Версия PHP: 7.4.21
Версия MySQL: 5.7.34

**Comment by Pathologic** [comment]
https://github.com/evocms-community/evolution/pull/49
