### ISSUE TITLE
[BUG] Where to set web user access rights?

### ISSUE THREAD

**Issue by leonie12** [evocms-community/evolution#150]
### Summary 
In former versions there was under the tab „User“ the possibility to set the access permissions to document groups etc. Since one of the latest updates it is no more there.

Also when accesing a ressource there was a tab access permissions, where one could set the user group for this ressource. This seems also to be disappeared …

Is this expected behaviour and these settings have been placed elsewhere, is it a bug in my installation or is it an issue with the actual release?

### Environment
EvoCMS version: Evo CE 3.1.12
Any relevant information:
FormLister/UserHelper installed, MODxApi installed. 
Logged in as administrator.
User mangement and access permissions are working fine. Just no possibility to find to set these access permissions.

**Comment by Pathologic** [comment]
Users - Permissions

**Comment by leonie12** [comment]
There was it indeed – before it disappeared.

Before it was Users – Web Users, Users - Roles and Users - Web Permissions

Now there is only Users - Web Users and Users - Roles

AND when editing a ressource the tab „Permissions“ also is not there any more, as written above. Actually it seems to be only possible to change ressource permissions using Doc Manager for Evo 3. At least here.

**Comment by Pathologic** [comment]
![image](https://user-images.githubusercontent.com/3012304/183306274-45756e7e-df82-43a7-8768-5b5baff53baf.png)

**Comment by leonie12** [comment]
Yes, this is where they were and where they are now not any more … 
Also the ressource permissions tab when editing a ressource is not any more there.
If I had a possibility to upload an image I would also post a screenshot, but I think it is also so evident: The blue permissions link is not there here. Before the last (?) update it was there and is there in an older local install. Otherwise everything works.

**Comment by leonie12** [comment]
After downloading, uploading and installing over and then logging out and in again everything is fine again. Before I had the error message that I (as Administrator) had not enough privileges to view the permissions page (?) …
No idea what the reason was.
