### ISSUE TITLE
[BUG] v3.1.12 User Permission issue

### ISSUE THREAD

**Issue by BBloke** [evocms-community/evolution#154]
This post may help but I'm not seeing what I would expect to see when duplicating permissions settings as for a v1.4 site.

https://forum.evo.im/d/262-v3-user-permissions-trouble

**Comment by Pathologic** [comment]
So, what's the issue? How to reproduce?

**Comment by BBloke** [comment]
The link should take you to an explanation.

It feels as though there is something granular missing.

I have a restricted area on my site.

admin
 > League (League Manager Group)
 > Division (Division Manager Group)
 > Standard (League Manager Group)
etc

Each child has the noted permission in paranthesis above.

My User is a League Manager.

A League Manager has access to all Groups, League, Division. When I sign in I do not see the Division page in the menu in v3 but I do with exactly the same permission setup in v1.4

Hope that helps.

**Comment by BBloke** [comment]
From looking at the differences in DLMenu I think I've narrowed it down to $modx->getUserDocGroups() the results between versions are different.

**Comment by BBloke** [comment]
Which in turn leads to:

core\vendor\evocms-services\user-manager\src\Services\Users\UserLogin.php line 331

```php
        $_SESSION[$this->context . 'Docgroups'] = \EvolutionCMS\Models\MemberGroup::query()
            ->join('membergroup_access', function($join) use ($context){
                $join->on('membergroup_access.membergroup', '=', 'member_groups.user_group');
                $join->on('membergroup_access.context', '=', \DB::Raw($context));
            })
            ->where('member_groups.member', $this->user->getKey())->pluck('documentgroup')->toArray();
```

which runs \EvolutionCMS\Models\MemberGroup but I'm lost from there.

It just isn't getting the array with the correct values for the document/user group.

**Comment by BBloke** [comment]
Here are the two SELECT statements from DLMenu from v1 and v3.  Notice the docgroups.  They are different and don't represent the users permissions in v3.

I don't think it is that. I download DocLister off github along with FormLister.

Here's the SELECT statements from DLMenu debug 2 from both sites!

v1.4
```mysql
SELECT 
  c.* 
FROM 
  `evo_site_content` as `c` 
  LEFT JOIN `evo_document_groups` as `dg` ON `dg`.`document` = `c`.`id` 
WHERE 
  c.id NOT IN (2, 4) 
  AND (
    `c`.`privateweb` = 0 
    OR `dg`.`document_group` IN (4, 3, 2, 5, 1)
  ) 
  AND c.parent IN ('0', '9') 
  AND c.id NOT IN('0', '9') 
  AND c.deleted = 0 
  AND c.published = 1 
GROUP BY 
  `c`.`id` 
ORDER BY 
  menuindex ASC
```
and in v3
```mysql
SELECT 
  c.* 
FROM 
  ep1h_site_content as `c` 
  LEFT JOIN ep1h_document_groups as `dg` ON `dg`.`document` = `c`.`id` 
WHERE 
  c.id NOT IN (2, 4) 
  AND (
    `c`.`privateweb` = 0 
    OR `dg`.`document_group` IN (1, 3, 4, 5, 4, 5, 1, 4, 5, 4)
  ) 
  AND c.parent IN ('0', '9') 
  AND c.id NOT IN('0', '9') 
  AND c.deleted = 0 
  AND c.published = 1 
GROUP BY 
  `c`.`id` 
ORDER BY 
  menuindex ASC
```

I would expect the docgroup in v3 to be identical to v1 but it isn't and doesnt reflect the group "Division Manager" ID 6.

**Comment by BBloke** [comment]
Been trying to track things down and the only thing I can come up with is that my installation has been caching things and causing chaos.

I did comment somethings out and try a few things which caused the session variable webDocGroups to be what it should be.

Happy with closing this.
