### ISSUE TITLE
[FEATURE] v3 User/Resources Group Link

### ISSUE THREAD

**Issue by BBloke** [evocms-community/evolution#155]
It would be great if there was an option for both web and mgr when creating user/resource group links.

It would also be great if the submitted options were retained when the screen refreshes to make creating multiple settings.

**Comment by Pathologic** [comment]
Maybe it would be better to change context select to checkboxes?

**Comment by BBloke** [comment]
That sounds like a great idea. You can at least select multiple options quicker especially with mgr and web options too.
