### ISSUE TITLE
migration script

### ISSUE THREAD

**Issue by cimt** [evocms-community/evolution#157]
i want to update from 1.4.20 to 3.1.12 but I can't find the migration script under Modules/Extras!

How else can I update?
via updater plugin? (but how?)
via installer script?

Please help... Thanks!

**Comment by Pathologic** [comment]
That script is not working with 3.1.12, so try to install manually from https://github.com/extras-evolution/migrate-evo

**Comment by cimt** [comment]
Hello Pathologic, thank you for your answer.
I took this one, the URL to the EVOCMS community is already inserted here...
https://github.com/BBloke/migrate-evo

**Comment by Pathologic** [comment]
> Hello Pathologic, thank you for your answer. I took this one, the URL to the EVOCMS community is already inserted here... https://github.com/BBloke/migrate-evo

I hope Barnsley will finish his module, so I'll add it to the extras.

**Comment by Pathologic** [comment]
![image](https://user-images.githubusercontent.com/3012304/188820924-0574fe8f-e122-4cda-9405-baeee212e2b9.png)
