### ISSUE TITLE
Installer script does not work with PHP 8

### ISSUE THREAD

**Issue by cimt** [evocms-community/evolution#161]
Hello @Pathologic
For information in advance:
Evolution CE 3.1.12 under PHP 7.4 and PHP 8.1

If i set in updater plugin 
**Commit branch: develop
Offer upgrade to stable version only: false**
i dont see the update Button on Dashbord!?

**Now the real problem:**

So I tried the installer script:
**from CE 3.1.12  to CE developer-Version 3.1.13 / PHP 8.1**
If i use Installer-Script, the installation process is aborted in the 2 or 3 step with a white page without displaying any errors!

with PHP 7.4 it works!!!

**Comment by Pathologic** [comment]
I've tried to install 3.1.13 with installer script and PHP 8.1 and there were no errors.

**Comment by cimt** [comment]
Hello @Pathologic, Yes, that works for me too!
**but...**
i would like to update an existing website with it... then in step 3, it breaks off with a white page!

**How can I update from CE 3.1.12 to a developer version with the updater plugin. like CE 3.1.13**

**SORRY! It's not urgent for me!!!**
Would just like to know if it works with the updater plugin!?

**Comment by Pathologic** [comment]
Closed as failed to reproduce.
