### ISSUE TITLE
Drop PHP 7.4 support

### ISSUE THREAD

**Issue by Pathologic** [evocms-community/evolution#168]
### Summary
7.4 will reach its end at 28 Nov 2022. Releases after this date will require PHP 8.1.

**Comment by 0test** [comment]
Нинада.

**Comment by sashabeep** [comment]
Не стОит...

**Comment by delphinpro** [comment]
Don't do this now.
When you upgrade to Laravel 9, you will have to remove support for PHP 7.4.

**Comment by Pathologic** [comment]
> Don't do this now. When you upgrade to Laravel 9, you will have to remove support for PHP 7.4.

That's why 3.1.13 seems to be the last release supporting PHP 7.4. Laravel 9 upgrade was ready 10 months ago (see 3.2 branch), but we ignored it because of PHP version requirements.

Don't know about 1.4.x, probably there's nothing that requires PHP 8.

**Comment by delphinpro** [comment]
Laravel 10 will be released in February 2023. You can jump right to Laravel 10 for 3.x =)

**Comment by delphinpro** [comment]
Version 1.4.x, I think, can be maintained for another year with php 7

**Comment by argalkin** [comment]
Зачем? Слетят многие компоненты

**Comment by Pathologic** [comment]
PHP 8.1 since 3.2.0
