### ISSUE TITLE
[BUG] php8.1 Array to string conversion in core\src\Core.php on line 4359

### ISSUE THREAD

**Issue by webber12** [evocms-community/evolution#170]
Стал ловить данную ошибку на этой строчке 

$arrPlaceholderFromSnippet = array_diff($arrPlaceholderCheckAfterSnippet, $arrPlaceholderCheck);

https://github.com/evocms-community/evolution/blob/3.x/core/src/Core.php#L4357 

Проблема в том, что array_diff не умеет в многомерные массивы.

**Comment by Pathologic** [comment]
Как воспроизвести?
