### ISSUE TITLE
[BUG] Визуальная ошибка при редактировании ролей

### ISSUE THREAD

**Issue by sashabeep** [evocms-community/evolution#172]
### Описание 
При сохранении роли пользователя не происходит возврат в раздел роли и нет переключателя "Сохранить+продолжить"

### Как воспроизвести
Создать новую или сохранить существующую роль

### Наблюдаемое поведение
Роль остается открытой

### Ожидаемое поведение
Возврат в список ролей

### Окружение
Версия EvoCMS: 3.1.12 CE
Версия PHP: 8.1
Другая информация:

https://user-images.githubusercontent.com/5689796/194505410-fc0b006c-459c-415c-939c-96b2bea85682.mp4

**Comment by 64j** [comment]
@sashabeep Во многих местах нет кнопки Сохранить + Продолжить, Сохранить + Создать новый, Сохранить + Закрыть.
Получается что Сохранить, вполне ожидаемое действие, а вот Отмена делает переход к списку.

**Comment by 64j** [comment]
fix https://github.com/evocms-community/evolution/commit/15d51db0d95e42d66dd4eab6450ac4222fefa6a1
