### ISSUE TITLE
remove "other" gender from edit user page

### ISSUE THREAD

**Issue by Pathologic** [evocms-community/evolution#183]
### Why is it needed?
Because there are only 2 genders: male and female. Ask any pathologoanatomist :laughing: 

### Related issue(s)/PR(s)
https://github.com/evocms-community/evolution/commit/4411258c6ddb102d607fa190ee21fcba50a32503

**Comment by bossloper** [comment]
Two sexes maybe. But gender can be considered a spectrum, so it depends what this field is recording.

**Comment by delphinpro** [comment]
Не принимая во внимание психологическое осознание себя, объективно, патологоанатомы также могут подтвердить, что существуют люди с двумя наборами первичных и вторичных половых признаков (пенис, влагалище, молочные железы).
