### ISSUE TITLE
site_name в шапке дерева

### ISSUE THREAD

**Issue by sashabeep** [evocms-community/evolution#197]
### Описание
Может, пора его выводить, раскодируя обратно?

### Зачем это нужно?
Выглядит неаккуратно

### Предлагаемое решение
Что-то поменять на выводе

![Снимок экрана 2022-12-06 в 15 54 58](https://user-images.githubusercontent.com/5689796/205918948-c8e0ce92-f3f6-46d1-9c99-4c6833563f91.png)
![Снимок экрана 2022-12-06 в 15 55 05](https://user-images.githubusercontent.com/5689796/205918959-0a0301cc-341e-4904-9c43-f9aea4416125.png)

**Comment by delphinpro** [comment]
https://github.com/evocms-community/evolution/blob/3.x/manager/views/frame/tree.blade.php#L56

Здесь не нужно преобразование html сущностей. Блэйд и так всё заэскейпит.
Решение: выводить `$modx->getConfig('site_name')` напрямую, без преобразований.
