### ISSUE TITLE
[BUG] Не сохраняются документы у не-админов

### ISSUE THREAD

**Issue by sashabeep** [evocms-community/evolution#202]
### Описание 
При сохранении документов вылезает ошибка
![IMAGE 2022-12-28 16:34:57](https://user-images.githubusercontent.com/5689796/209820375-b5cb8525-3b1d-42f2-9e3b-91e4ae0449c4.jpg)

### Как воспроизвести
Открытие и сохранение документов.
Пользователь editor в группе админов, связанных с группой ресурсов в контексте mgr. Но сам документ без прав (доступен всем). При редактировании никаких прав не меняется, нет необходимости

### Наблюдаемое поведение
Редактор не может сохранить документ

### Ожидаемое поведение
???

Документ сохраняется если снять галку у роли
![Снимок экрана 2022-12-28 в 16 31 55](https://user-images.githubusercontent.com/5689796/209820578-b081148f-9289-4a81-b21d-a43b40af0a72.png)

### Окружение
Версия EvoCMS: 3.1.12

Это наверное уже фиксили, да?

**Comment by Pathologic** [comment]
Да
