### ISSUE TITLE
Прозрачные защищенные ресурсы в дереве

### ISSUE THREAD

**Issue by sashabeep** [evocms-community/evolution#207]
До сих пор не очень понятно, что это означает. Залогинен от менеджера, который имеет доступ к группе, в которой спрятаны технические страницы. Я могу их редактировать, создавать и всё такое, но зачем они прозрачные, если у меня есть к ним доступ?

<img width="283" alt="Снимок экрана 2023-01-02 в 00 21 17" src="https://user-images.githubusercontent.com/5689796/210184937-8cdac954-ab4e-44b2-a108-be2efba4d173.png">

**Comment by Pathologic** [comment]
Если у менеджера есть доступ к защищенным от менеджеров ресурсам, то они полупрозрачные.
