### ISSUE TITLE
Предупреждение о правах на конфиг соединения с БД

### ISSUE THREAD

**Issue by sashabeep** [evocms-community/evolution#216]
### Описание
В админке не показывается предупреждение, что файл /core/config/database/connections/default.php всё ещё доступен для записи, если на нем права 777

### Зачем это нужно?
Чтобы было как раньше с файлом /manager/includes/config.inc.php

**Comment by delphinpro** [comment]
А другие конфиги чем отличаются от коннекта? Или на все нужно ридонли делать?
Абсолютно бесполезная фишка. По крайней мере в трешке.

**Comment by Pathologic** [comment]
Мне и с файлом config.inc.php не очень понятно, в чем смысл ставить на него особые права, если их в 99% случаев можно переопределить программно, ну и файл в любом случае доступен для чтения, то есть несложно узнать данные для подключения к базе.

**Comment by sashabeep** [comment]
Ну если это ни на что не влияет тогда и не нужно, конечно. Вроде как раньше можно было как-то его запустить, зная ссылку на него, хотя, он и раньше ничего не выводил, только содержал набор констант. Ну при установке на него какие-то ограничивающие права устанавливаются вроде
