### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by 0test** [evocms-community/evolution#24]
### Описание 
Ошибка
`Too few arguments to function Illuminate\Database\Eloquent\Model::destroy(), 0 passed in \core\src\Core.php on line 3100 and exactly 1 expected`

### Как воспроизвести
1. "Использовать AliasListing только для Папок" - Да.
2. Перейти на любой урл типа имясайта/2 (любая цифра)

### Ожидаемое поведение
А должна быть 404

### Окружение
Версия EvoCMS: 3.1.9
Версия PHP: 7.4
Версия MySQL:  8.0.24

**Comment by Pathologic** [comment]
Проблема в методе getChildIds()

**Comment by 0test** [comment]
Я балбес или фиксы надо?
