### ISSUE TITLE
[BUG] Отключение редактора у документа странно выглядит странно

### ISSUE THREAD

**Issue by sashabeep** [evocms-community/evolution#240]
### Описание 
Если в настройке страницы снять галку "Использовать HTML редактор" и пересохранить документ то поле становится очень большим по высоте

![Снимок экрана 2023-02-09 в 12 01 01](https://user-images.githubusercontent.com/5689796/217765403-bb4bd3ee-aa3c-4574-978a-bfd7b7fe8164.png)

А было так
![Снимок экрана 2023-02-09 в 12 02 44](https://user-images.githubusercontent.com/5689796/217765805-e588568e-4bf7-4aae-8d88-819005a94500.png)

### Окружение
Версия EvoCMS: 3.1.15

**Comment by Pathologic** [comment]
Так и должно быть.
