### ISSUE TITLE
FormLister 1.19.5 no messages output

### ISSUE THREAD

**Issue by cimt** [evocms-community/evolution#245]
Hello @Pathologic

Evolution CE 3.1.15
PHP Version 8.1.10 
**FormLister 1.19.5** [+form.messages+] **no output**, and no error is shown either.

Evolution CE 3.1.15
PHP Version 8.1.10 
**FormLister 1.19.3** ... [+form.messages+] **works fine**.

**Comment by Pathologic** [comment]
Ok, waiting for somebody with telepathic abilities to reproduce.

**Comment by cimt** [comment]
@Pathologic ... sorry, i forgot:

`&messagesTpl='@CODE:<div class="errors"><b>Info:</b><br>[+required+]<br>[+errors+]<br>[+messages+]</div>' `

Is a simple contact form!

**Comment by Pathologic** [comment]
It worked only with [+messages+], fixed.
