### ISSUE TITLE
Ошибка при создании копии ресурса [BUG]

### ISSUE THREAD

**Issue by Grinyaha** [evocms-community/evolution#250]
Если в настройках выставлено -> Минимальный пропущенный ID, то копия ресурса не создается. Ошибка 
`« Evolution CMS Parse Error »
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'evo_(site_content.id+1)' in 'on clause' (SQL: select min(`evo_site_content`.`id`) as aggregate from `evo_site_content` left join `evo_site_content` as `evo_T1` on `evo_(site_content`.`id+1)` = `evo_T1`.`id` where `evo_T1`.`id` is null)`

**Comment by delphinpro** [comment]
Эту настройку и функционал вообще следует удалить из системы. Оставить только автоинкремент.

**Comment by Grinyaha** [comment]
> Reference

Если вы ей не пользуетесь, это не значит что ее надо удалить. В 1.4 все отлично работает.

**Comment by delphinpro** [comment]
Дело не в том, что я не пользуюсь. Суть в том, что сам по себе это бесполезный функционал. Уникальный идентификатор для данных есть - автоинкремент в базе. Если вам нужен порядковый номер для вашей бизнес-логики - заводите отдельное поле в таблице и следите за его корректностью. Использовать для этого примари-кей - хрень полная. Это не только  мое мнение.

**Comment by Grinyaha** [comment]
Так если он свободный, проблем вообще нет и на базу никак не влияет.

**Comment by Pathologic** [comment]
Могут быть проблемы из-за этого.

**Comment by Pathologic** [comment]
Проблема не столько в этом запросе, который еще и выполняется дважды, сколько в том, что документы создаются через модель, которая не позволяет задавать ID. То есть даже при исправленном запросе эта настройка работать не будет. Я склоняюсь к тому, что настройку нужно удалить. Странно, что ты не заметил, что настройка не работает и при создании нового документа.
