### ISSUE TITLE
[BUG] Невозможно скрыть средствами templatesEdit3 TV-параметры для пользователей определенной роли

### ISSUE THREAD

**Issue by OlegGilyazov** [evocms-community/evolution#251]
Проблема явно не в templatesEdit3, т.к. одна и та же его версия (3.1.9) стоит на двух сайтах, одна Evo – 3.1.10 , другая Evo – 3.1.15, на первом работает, на втором нет.

**Comment by Pathologic** [comment]
Воспроизвести как?

**Comment by OlegGilyazov** [comment]
Вот тут последовательность действий и скрины: https://docs.google.com/document/d/1sz3erI51Totz2wgC9v2VpO9pEQ9tJ82T_3N4F3jFg4Y/edit?usp=sharing
При необходимости могу дать доступ к админке (в телеграме)

**Comment by 64j** [comment]
@OlegGilyazov 
Попробуйте убрать зелёную галочку рядом с названием Таба. Чтобы она стала серой
