### ISSUE TITLE
[BUG] открывается страница из не своего родителя

### ISSUE THREAD

**Issue by helgispbru** [evocms-community/evolution#252]
### Описание 

Есть 2 страницы, которые находятся рядом, на первом уровне: `/dostavka` и `/garantia`
Если перейти по `/dostavka/garantia` то открывается гарантия, ведь последний элемент адреса это нормальная страница и она есть в дереве и всё хорошо.
Если перейти по `/garantia/dostavka` то открывается доставка, да.
Можно открывать даже `/dostavka/garantia/dostavka` и получать доставку.
Или даже  `/korzina/zakaz/oplata/dostavka/garantia` и получать гарантию.

### Ожидаемое поведение

Наверное должна быть проверка нахождения ресурса и если ресурс есть, но адрес до него неправильный, то выдавать 404. 
Или это поведение нормальное и багом не считается.

### Окружение
Версия EvoCMS: 3.1.15

**Comment by helgispbru** [comment]
Есть подозрение, что это у меня на сайте что-то накручено и поэтому оно так работает. 
На пустом тестовом сайте такого поведения найти не удалось.

**Comment by Pathologic** [comment]
https://github.com/evocms-community/evolution/commit/7a14b39643eb3934b4a643757b991e69b691d37c

**Comment by 64j** [comment]
@Pathologic 
Только урл вида **/dostavka/garantia/dostavka** переходит на **/dostavka**, остальные все 404 показывают

**Comment by helgispbru** [comment]
@Pathologic у меня нормально.
Ситуация /dostavka/garantia/dostavka переходит на /dostavka с 301-ым редиректом, что вполне хорошо.
Я не нашёл проблем в итоге.

**Comment by Pathologic** [comment]
Ничего не хорошо, /dostavka/garantia/dostavka показывает страницу доставка с кодом 200, без всяких редиректов.

**Comment by Pathologic** [comment]
https://github.com/evocms-community/evolution/commit/04f9cffb1448990bde5a08f12707e6d3fadadfaf

**Comment by helgispbru** [comment]
Свежеустановленная версия.

Я проверил все варианты:
/dostavka.html
/dostavka/oplata/dostavka.html
/dostavka/dostavka.html

И для всех трёх вариантов alias listing:  full, folders, none

У меня везде, если неправильная ссылка, выдаёт 404 как и должно быть.
