### ISSUE TITLE
Убирать isfolder при удалении всех дочерних

### ISSUE THREAD

**Issue by helgispbru** [evocms-community/evolution#260]
### Описание
При удалении последнего дочернего документа у ресурса снимать у этого ресурса галочку isfolder. 
Добавить такую проверку и обработку в вызов очистки корзины удалённых ресурсов.

Для версии 3.х

**Comment by Pathologic** [comment]
А в какой момент галочку снимать - когда ресурсы удалены, или когда корзина очищена? В любом случае, это можно сделать плагином.

**Comment by helgispbru** [comment]
Плагин да, конечно.
Я вижу это так - при очистки корзины для каждого удаляемого ресурса проверяется последний ли он у родителя. Если последний, то у родителя снимается isfolder. 
Ведь при добавлении дочернего ресурка isfolder ставится?  Вот, а тут будет обратный процесс.

**Comment by Pathologic** [comment]
При добавлении ставится, чтобы ты эти дочерние вообще увидел в дереве. А зачем обратный процесс, я не знаю. Ну и я помню, что иногда искал с isfolder=1, то есть где-то может поломаться.
