### ISSUE TITLE
Remove help page from manager, replace it with dashboard widget

### ISSUE THREAD

**Issue by Pathologic** [evocms-community/evolution#261]
### Summary
Help page is useless and outdated, so it would better to remove it from manager. A plugin to create dashboard widget with actual links would be a better solution.

**Comment by fourroses666** [comment]
Agree. Could be an "About Evolution CMS" widget. Maybe someone has better idea's.

**Comment by Pathologic** [comment]
https://github.com/evocms-community/evolution/commit/6dfc55388576d423490126b7422be3bd1d068d91
