### ISSUE TITLE
Добавить artisan make:seeder

### ISSUE THREAD

**Issue by helgispbru** [evocms-community/evolution#262]
### Описание
По аналогии с командой `php artisan make:migration` добавить команду `php artisan make:seeder`

### Зачем это нужно?
Создание шаблонов сидеров автоматически

**Comment by helgispbru** [comment]
Команда `composer dump-autoload` кажется не проверяет папку `/core/database/seeds`, тоже надо проверить.

**Comment by AgelxNash** [comment]
Все очень интересно, а какой эффект ожидается на выходе? Получить пустой файл в стиле 
```<?php

namespace EvolutionCMS\XXXXXXXXXX;

use Illuminate\Database\Seeder;

class XXXXXXXXXSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        
    }
}```

**Comment by projkin** [comment]
+ к Seeders еще и specific evocms db FakeFactory's было бы неплохо. Фейк данные для базового заполнение в купе с сидерами неплохо ускоряют
