### ISSUE TITLE
1.4.x [BUG] индикатор занятого элемента в админке

### ISSUE THREAD

**Issue by sashabeep** [evocms-community/evolution#283]
### Описание 
Если другой администратор редактирует плагин, вместо значка показывается кусок тэга

### Как воспроизвести
Зайти в список элементов, один из которых открыт другим администратором

### Наблюдаемое поведение
![Снимок экрана 2023-05-18 в 12 34 34](https://github.com/evocms-community/evolution/assets/5689796/204433a4-3648-43ab-8c3c-43f9240f1af7)

### Ожидаемое поведение
Вроде должен быть значок глаза (или замка?) вместо тэга

### Связанные issue(s)/PR(s)
Укажите, если это сообщение относится к имеющимся issues или PRs.

### Окружение
Версия EvoCMS: Evolution CE 1.4.24

**Comment by Pathologic** [comment]
Не воспроизводится.

**Comment by autogen-travel** [comment]
Воспроизводится, причем сто лет уже как
![image](https://github.com/evocms-community/evolution/assets/13348823/663be824-e392-42e4-b1d9-1d7ee2e711e0)

**Comment by Pathologic** [comment]
https://github.com/evocms-community/evolution/commit/1ca71935128621a5fc984b915c3c1e9704e218df
