### ISSUE TITLE
sendRedirect ограничен только 30x кодами, почему?

### ISSUE THREAD

**Issue by helgispbru** [evocms-community/evolution#289]
### Описание

Нашёл в документации и подтверждение в коде (ссылка ниже), что sendRedirect ограничен только 30х кодами.
Столкнулся с этим когда было нужно возвращать 410 Gone, но всё равно получал 302 Moved Tepmorarily.

Предлагаю убрать это ограничение, пусть будет возможность использовать любой их доступных кодов.

https://github.com/evocms-community/evolution/blob/cff7713a28e4dd11fa065a4a347d377370fba5d0/core/src/Core.php#LL458C1-L460C10

### Предлагаемое решение

Убрать ограничение на коды.

**Comment by Pathologic** [comment]
Потому что коды 30x предназначены для редиректов.
