### ISSUE TITLE
[Bug] release package 3.1.19 installs the wrong version 3.2.0

### ISSUE THREAD

**Issue by sirfranz** [evocms-community/evolution#293]
### Summary

There is something wrong with release "Evolution CE 3.1.19": instead of 3.1.19 this package will install 3.2.0.

### Steps to reproduce.

try setup

### EvoCMS version

3.1.19

**Comment by Pathologic** [comment]
Sorry :disappointed: You can reinstall manually with [installer](https://github.com/evocms-community/installer) or stay with 3.2.0 - it has Laravel 9 included and requires PHP 8.1, that's the only difference.
