### ISSUE TITLE
[Bug] Хелпер phpthumb не находит картинку "no image"

### ISSUE THREAD

**Issue by sashabeep** [evocms-community/evolution#305]
### Описание

При вызове типа
```
{{\Helper::phpThumb($data['tv.image'], 'w=80,h=80,zc=1')}}
```
при пустой data ругается на отсутствующую картинку

**assets/images/noimage.png**

### Версия EvoCMS

Evolution CE 3.1.20

### Версия PHP

8.1.20

**Comment by ProjectSoft-STUDIONIONS** [comment]
https://github.com/evocms-community/docs/blob/master/ru/04_Компоненты/phpthumb/03_Параметры.md#collapse1593

**Comment by sashabeep** [comment]
> [https://github.com/evocms-community/docs/blob/master/ru/04_Компоненты/phpthumb/03_Параметры.md#collapse1593](https://github.com/evocms-community/docs/blob/master/ru/04_%D0%9A%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B/phpthumb/03_%D0%9F%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D1%8B.md#collapse1593)

Хелпер и сниппет - разные

**Comment by ProjectSoft-STUDIONIONS** [comment]
> > [https://github.com/evocms-community/docs/blob/master/ru/04_Компоненты/phpthumb/03_Параметры.md#collapse1593](https://github.com/evocms-community/docs/blob/master/ru/04_%D0%9A%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B/phpthumb/03_%D0%9F%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D1%8B.md#collapse1593)
> 
> Хелпер и сниппет - разные

В какую сторону копать. Всё решаемо.

**Comment by Pathologic** [comment]
```
{{\Helper::phpThumb($data['tv.image'], 'w=80,h=80,zc=1', ['noImage' => 'assets/images/noimage.jpg'])}}
```
Ну или положить картинку в assets/images/
