### ISSUE TITLE
[Bug] вывод [*tvname*] внутри контента не обрабатывается парсером

### ISSUE THREAD

**Issue by sashabeep** [evocms-community/evolution#308]
### Описание

Если вставить в контент тв-параметр этого же ресурса, он так и выведется [ * tvname * ] вместо значения

### Версия EvoCMS

Evolution CE 1.4.29

### Версия PHP

7.4

**Comment by Pathologic** [comment]
Не воспроизводится

**Comment by Pathologic** [comment]
![image](https://github.com/evocms-community/evolution/assets/3012304/f3cb0424-fe9a-4665-a561-9bf0fe18fd0b)
