### ISSUE TITLE
[Bug] Смена роли пользователя при создании провоцирует перезагрузку страницы

### ISSUE THREAD

**Issue by sashabeep** [evocms-community/evolution#309]
### Описание

С всплывающим окном текста смены шаблона. Все введенные поля стираются
![Снимок экрана 2023-07-04 в 17 40 27](https://github.com/evocms-community/evolution/assets/5689796/b486b59c-763e-4c38-971f-4abbd7fd320a)

### Как воспроизвести.

Начать создавать пользователя и сменить роль

### Наблюдаемое поведение

Страница перезагружается при смене роли

### Ожидаемое поведение

Страница не должна перезагружаться

### Версия EvoCMS

Evolution CE 3.1.20

### Версия PHP

8.1.20

**Comment by Pathologic** [comment]
Почему не должна? Это сделано, чтобы тв-параметры подгружались.

**Comment by sashabeep** [comment]
@Pathologic Понятно. Может, другой текст в окне тогда выводить, а то выглядит странно. И поля все сбрасываются, не круто, конечно. Может, роль тогда в самый верх надо передвигать
