### ISSUE TITLE
PHP 8.2 and  EVO 1.4.29 

### ISSUE THREAD

**Issue by user83743** [evocms-community/evolution#311]
Hi Evo People,

do you have php 8.2 and EVO 1.4.29 working well together on some of your sites?  

i switched over to php8.2 on a text site with evo1.4.29 and the site works fine but if i use the MANAGER, I get error_log entries in /manager/error_log , ever time i use the evo manager --- like these:

[10-Aug-2023 08:34:12 UTC] PHP Warning: Array to string conversion in /home/dsrservices/public_html/xxxx.com/assets/lib/class.modxRTEbridge.php on line 839
[10-Aug-2023 08:34:12 UTC] PHP Warning: Array to string conversion in /home/dsrservices/public_html/xxxx.com/assets/lib/class.modxRTEbridge.php on line 839
[10-Aug-2023 08:34:12 UTC] PHP Warning: Array to string conversion in /home/dsrservices/public_html/xxxx.com/assets/lib/class.modxRTEbridge.php on line 839
[10-Aug-2023 08:34:12 UTC] PHP Warning: Array to string conversion in /home/dsrservices/public_html/xxxx.com/assets/lib/class.modxRTEbridge.php on line 839

any ideas?

**Comment by Pathologic** [comment]
I've checked a site built on 1.4.29 with PHP 8.2 and see no warnings. You should provide more infornation to reproduce this issue.

**Comment by user83743** [comment]
Hi Pathologic

Thanks for the update. If we go to the public website, we see no errors. If we log into the /manager and edit some resources or web pages- then we see those error logs in /manager/error_log

**Comment by Pathologic** [comment]
Is 839 line at your installation the same as here? https://github.com/evocms-community/evolution/blob/1.4.x/assets/lib/class.modxRTEbridge.php#L839

**Comment by user83743** [comment]
yes, my line 839 is the same as above  https://github.com/evocms-community/evolution/blob/1.4.x/assets/lib/class.modxRTEbridge.php#L839

**Comment by Pathologic** [comment]
What is your TinyMCE configuration?

**Comment by Pathologic** [comment]
Ok, I see these warnings are summoned with richtext TVs.

**Comment by user83743** [comment]
here is tinymce config settings:



Parameter	Value	

Custom Style Formats RAW     [[[   ]]]] "empty"


Custom Style Formats INLINE           InlineTitle,cssClass1|InlineTitle2,cssClass2


Custom Style Formats BLOCK              BlockTitle,cssClass3|BlockTitle2,cssClass4

 
Custom Parameters             [[[   ]]]] "empty"      

	
Entity Encoding	                       named

Entities	                 [[[   ]]]] "empty"

Path Options	              Site config


Advanced Resizing	       false

Disabled Buttons	      [[[   ]]]] "empty"

Web Theme	             webuser

Web Plugins	            [[[   ]]]] "empty"

Web Buttons 1	            bold italic underline strikethrough removeformat alignleft aligncenter alignright

Web Buttons 2	            link unlink image undo redo

Web Buttons 3	             [[[   ]]]] "empty"

Web Buttons 4	             [[[   ]]]] "empty"

Web Toolbar Alignment	      ltr

Width	              100%

Height	              400px

Introtext RTE           disabled

Inline-Mode	      disabled

Inline-Mode            inline

Browser Spellcheck          disabled

Force Paste as Text	      disabled

Static file path             [[[   ]]]] "empty"

**Comment by Pathologic** [comment]
Now you can update to 1.4.30, the bug is fixed.

**Comment by user83743** [comment]
mighty work as usual Pathlogic. i upgraded to evo1.4.30 and then edited a resource-page, template, chunk, snippet etc and no more manager/error_log file entries. super work
