### ISSUE TITLE
[Bug] Управление пакетами 0.1.3

### ISSUE THREAD

**Issue by XTRO123** [evocms-community/evolution#314]
### Описание

После установки любого модуля некорректная работа в блоке .install_extras (отсутствует надпись об установленном пакете, текста на кнопке о переустановке и соотв. предупреждений из data-text)

![evo_mod_bug_2023-08-27_22-39](https://github.com/evocms-community/evolution/assets/2737316/a1ee84b0-e460-462f-bbc8-f3ac99b8d142)

### Как воспроизвести.

установить любой модуль и попытаться его переустановить

### Наблюдаемое поведение

логика работы с модулем не меняется, нет "Переустановить" и соотв. предупреждений из data-text

### Ожидаемое поведение

смена кнопки с текстом и появления предупреждений

### Версия EvoCMS

3.1.20

### Версия Apache/nginx

2.4.52

### Версия PHP

8.1.2

### Версия MySQL

8.0.34

**Comment by sashabeep** [comment]
@XTRO123 В системе нет понятия пакет и способов его идентицикации. Установка - это только скачивание и распаковка файлов и выполнение импорта в БД, если понадобится.

**Comment by XTRO123** [comment]
@sashabeep Для описания ситуации я использую терминологию, видимую на экране. Для этого достаточно посмотреть на скриншот.

**Comment by sashabeep** [comment]
> @sashabeep Для описания ситуации я использую терминологию, видимую на экране. Для этого достаточно посмотреть на скриншот.

Да всё понятно, я не это имел в виду, в системе действительно нет понятия пакет. В рево у каждого дополнения есть некий уникальный идентификатор, который прописывается при установке, в эво просто вообще нет ничего подобного, "пакет" и версии его нигде не прописываются и не хранятся

**Comment by XTRO123** [comment]
я видел исходник )) если  мы хотим качество кода, должны тогда обязаны найти решение.  Лучше в телеге обсуждать сабж.
