### ISSUE TITLE
[Bug] ошибка при обновлении artisan make:site update

### ISSUE THREAD

**Issue by XTRO123** [evocms-community/evolution#317]
### Описание

выполнение команды artisan make:site update 3.x приводит к крашу и 500_ой.  
![Снимок экрана от 2023-09-05 23-36-49](https://github.com/evocms-community/evolution/assets/2737316/942f409f-76df-413b-8e9e-8eef786a7b74)

### Как воспроизвести.

php artisan make:site update 3.x

### Наблюдаемое поведение

500 err

### Версия EvoCMS

3.1.20

### Версия Apache/nginx

2.4.52

### Версия PHP

8.1.2

### Версия MySQL

8.0.34

### Другая информация

Восстановить работоспособность можно после выполнения composer update

**Comment by Pathologic** [comment]
С какой версии обновление?

**Comment by XTRO123** [comment]
3.1.20

**Comment by Pathologic** [comment]
С 3.1.20 на 3.1.20?

**Comment by Pathologic** [comment]
Проверил для 3.1.19 -> 3.1.20 - нет ошибок. Запускать второй раз artisan make:site update не имеет смысла, потому что файлы уже скачаны и распакованы. Нужно сделать composer update, а потом php  ../install/cli-install.php --typeInstall=2 --removeInstall=y чтобы завершить обновление.

**Comment by XTRO123** [comment]
естественно на текущейсмысла нет, но это не отменяет возможность пользователю через неделю запустить эту команду (для проверки) при текущей версии. Думается нужна просто проверка на свежесть.
