### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by XTRO123** [evocms-community/evolution#327]
### Описание

Админка. Добавляя к ресурсу одиночный tv image 
![image](https://github.com/evocms-community/evolution/assets/2737316/7e78d05b-9ac2-43ea-bd19-6f60e454f168)
получаем дублирование у ресурса отображения этого  img, т.к. thumb  уже отработал.  
![image](https://github.com/evocms-community/evolution/assets/2737316/e4fefe71-c25a-44fe-a3b3-d8bff1a3c03a)
Удаляя 898 - 900 получаем правильное отображение . https://github.com/evocms-community/evolution/blob/69e014bb9222afd15e6ecda30f879184660d581f/core/functions/actions/mutate_content.php#L898C31-L898C31 

### Как воспроизвести.

добавить tv img

### Наблюдаемое поведение

двойная картинка

### Ожидаемое поведение

1 картинка

### Версия EvoCMS

3.1.20

### Версия Apache/nginx

2.4.52

### Версия PHP

8.2

### Версия MySQL

8.0.34

**Comment by Pathologic** [comment]
отключаем MM
