### ISSUE TITLE
Сохранение Emoji [Bug] 

### ISSUE THREAD

**Issue by ProjectSoft-STUDIONIONS** [evocms-community/evolution#350]
### Описание

При сохранении текста содержащий Emoji текст обрезается или вообще удаляется.
Зависит от используемых символов.
Новый документ -> Вставить строку
````
😀 😃 😄 😁 😆 😅 😂 🤣
````
Строка не сохранится.

### Версия EvoCMS

1.4.x

**Comment by Pathologic** [comment]
![image](https://github.com/evocms-community/evolution/assets/3012304/50a9992e-6dc7-4b3e-bc53-9a3a30c36013)
![image](https://github.com/evocms-community/evolution/assets/3012304/4f463452-1ef5-427d-860c-2af36ea6dd2b)

**Comment by Pathologic** [comment]
Нужно проверять настройки подключения к базе и кодировку.
