### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sahar-08** [evocms-community/evolution#354]
### Описание

Кстати если в базе есть запись в site_name и settings.php прописать site_name, то выводится по дефолту из базы, не комильфо =(
А если в базе пусто, то  пустота и выводится

### Как воспроизвести.
Вывести EvolutionCMS()->config['site_name'] В шаблоне на фронте

### Версия EvoCMS

3.1.21

### Версия Apache/nginx

2,4

### Версия PHP

8.2

### Версия MySQL

8

**Comment by Pathologic** [comment]
![image](https://github.com/evocms-community/evolution/assets/3012304/c721c9f2-e37d-4b88-b90a-5b50671c6d08)

**Comment by Pathologic** [comment]
![image](https://github.com/evocms-community/evolution/assets/3012304/e0351c76-5e34-407d-8ab5-f15d7aad37a3)

**Comment by sahar-08** [comment]
А на фронте?

**Comment by sahar-08** [comment]
![image](https://github.com/evocms-community/evolution/assets/22763261/657bb98d-7e6e-4782-90bb-e452189af732)

**Comment by sahar-08** [comment]
![image](https://github.com/evocms-community/evolution/assets/22763261/664e213d-c3e1-434a-be18-b2cbb251d6c1)

**Comment by Pathologic** [comment]
И на фронте из файла.

**Comment by XTRO123** [comment]
из файла имеет приоритет...это есть в доках https://github.com/0test/evo-newdocs/blob/main/v3/01_Начало%20работы/003_Конфигурация.md

**Comment by sahar-08** [comment]
Блин ну на скирнах же видно что из базы берется

**Comment by sahar-08** [comment]
![image](https://github.com/evocms-community/evolution/assets/22763261/4d3c8cbc-4b2e-4410-bd4e-7f8857fea643)

**Comment by sahar-08** [comment]
![image](https://github.com/evocms-community/evolution/assets/22763261/b16dc61d-9c77-4685-8c4b-0252aa23feec)

**Comment by Pathologic** [comment]
Используй `evo()->getConfig('site_name')`

**Comment by sahar-08** [comment]
И кстати тоже не работает
