### ISSUE TITLE
не видит заполненный .env   [Bug] 

### ISSUE THREAD

**Issue by XTRO123** [evocms-community/evolution#357]
### Описание

Вот [здесь ](url=https://github.com/evocms-community/evolution/blob/81d4250cd50cf3c78ed2d356ec7387d5b56e5fc8/core/bootstrap.php#L16C15-L16C15) имеем пустую переменную, хотя в глобальном $_ENV всё есть. В результате данных из .env нет и получаем 503

### Как воспроизвести.

взять проект с боевого сервера и поднять на локальном или сделать разные конфиги для dev и prod

### Наблюдаемое поведение

503 ошибка

### Версия EvoCMS

3.1

### Версия Apache/nginx

2.4.56

### Версия PHP

8.2.4 

### Версия MySQL

8

### Другая информация

![Скриншот 05-12-2023 165742](https://github.com/evocms-community/evolution/assets/2737316/d00122c1-2f6c-43ce-b83c-529f86261bc6)
![image](https://github.com/evocms-community/evolution/assets/2737316/5507183e-7b62-4700-aa93-305466c76b04)

**Comment by XTRO123** [comment]
чистая локальная установка (для теста) привела к ситуации:  устанавливаем, создаём .env. После создания .env появилось "A possible CSRF attempt was detected from referer" . Чистка cache и storage не помогла. Удаление .env вернуло полную работоспособность.

**Comment by Pathologic** [comment]
Не воспроизводится.
