### ISSUE TITLE
[Bug]  Duplicate declaration of static variable 

### ISSUE THREAD

**Issue by XTRO123** [evocms-community/evolution#362]
### Описание

https://github.com/evocms-community/evolution/blob/0f3d9384170209ac2c772eabc1afb199c230f683/core/functions/actions/mutate_content.php#L857
https://github.com/evocms-community/evolution/blob/0f3d9384170209ac2c772eabc1afb199c230f683/core/functions/actions/mutate_content.php#L828

### Наблюдаемое поведение
![20-12-2023 004527](https://github.com/evocms-community/evolution/assets/2737316/489d49f2-eb10-417c-9ce7-6c8039dd6acb)

_No response_

### Версия EvoCMS

3.1.x

### Версия Apache/nginx

Apache/2.4.56

### Версия PHP

8.3

### Версия MySQL

 10.4.28-MariaDB

**Comment by Pathologic** [comment]
https://github.com/evocms-community/evolution/commit/7360632e185dfe16d3c57be4bab75bcd747dc015

Fixed in 3.3.1.
