### ISSUE TITLE
Blank frontend and backend when switching to PHP8.3 [Bug] 

### ISSUE THREAD

**Issue by leonie12** [evocms-community/evolution#363]
### Summary

When I switch the PHP version at my webhost to 8.3 the frontend and backend of different websites remain blank without any error message or error log entry.

### Steps to reproduce.

Switch PHP version from 8.2 to 8.3

### Observed behavior

Frontend and backend remain blank.

Changing back to PHP 8.2 and everything works again …

### Expected behavior

Everything should work as with PHP 8.2 before.

### EvoCMS version

CE 3.1.24

### PHP version

8.3

### Any relevant information

PHP 8.3 is out for some days. Is there actually support for PHP 8.3 in Evo 3.1.24 or 3.2?

**Comment by Pathologic** [comment]
Try 3.3.x branch.
