### ISSUE TITLE
[Bug] наложение иконок в админке

### ISSUE THREAD

**Issue by XTRO123** [evocms-community/evolution#367]
### Описание

при вертикальном расположении меню в админке слева [(manager_menu_position)]   на кнопку "Конфигурация" (<li id="system">)   наезжает кнопка - "На полный экран" (<li id="fullscreen">), что не даёт нажать на "Конфигурация".
![Скриншот-24-12-2023 21_55_32 (1)](https://github.com/evocms-community/evolution/assets/2737316/889a641a-0035-4044-ba54-3848612128db)

### Как воспроизвести.

[(manager_menu_position)] установить слева

### Наблюдаемое поведение

[видео](https://skrinshoter.ru/v/241223/2CrKyfV9.mp4?view=1&name=Видео-24-12-2023%2021:51:09.mp4)

### Версия EvoCMS

3.2.1

### Версия PHP

8.2.4

**Comment by Pathologic** [comment]
Не воспроизводится.

**Comment by Pathologic** [comment]
Есть наложение иконок, когда высота экрана недостаточная, а такого как в видео - нет.

**Comment by XTRO123** [comment]
перепроверил на двух разных мониторах, в т.ч. 4К https://skr.sh/sNZPtApJxpd.jpg под разными броузерами - FF, Ch, Y

**Comment by Pathologic** [comment]
![image](https://github.com/evocms-community/evolution/assets/3012304/dfe163d8-4c1f-48f3-a276-b4c2b9c212b7)

Этих иконок внизу вообще быть не должно. Плагин какой-то наверное.

**Comment by XTRO123** [comment]
почему? одна иконка - fullcsreen- если включен [(show_fullscreen_btn)] , вторая - system. На вашем вскрине только system, а воторой вообще нет.... ее можно увидеть после включения [(show_fullscreen_btn)] отдельно, если увеличть на 1 rem`  .navbar-left #mainMenu #settings.nav > #fullscreen
{ bottom: 6rem;  }` 
![изображение](https://github.com/evocms-community/evolution/assets/2737316/6788299d-99b5-487f-b164-84ac32685250)

**Comment by sashabeep** [comment]
Эта кнопка, как и кнопка магазина - от ClientSettings и от Commerce
![изображение](https://github.com/evocms-community/evolution/assets/5689796/c6ba2252-705b-4771-a081-8adbe0a34a9b)

**Comment by Pathologic** [comment]
> Эта кнопка, как и кнопка магазина - от ClientSettings и от Commerce ![изображение](https://private-user-images.githubusercontent.com/5689796/302618504-c6ba2252-705b-4771-a081-8adbe0a34a9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjg4MTQsIm5iZiI6MTcwNzIyODUxNCwicGF0aCI6Ii81Njg5Nzk2LzMwMjYxODUwNC1jNmJhMjI1Mi03MDViLTQ3NzEtYTA4MS04YWRiZTBhMzRhOWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDZUMTQwODM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDJkZGExMGRiMjdjNmRiM2MxM2Y5OWIzM2UzYmE3ODlhMWI1NzNkNWM4NzRiOGJkN2UwMWQzOWZiZWRlYmM4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LiWHWwHu-Xm0lZeddU-M5Xpl3kiz7iELAU0uBR8jtXU)

Я тоже так думал, но она в настройках включается на самом деле.
