### ISSUE TITLE
[Bug] Невозможно сохранить пользовательские настройки

### ISSUE THREAD

**Issue by delphinpro** [evocms-community/evolution#372]
### Описание

Кнопка сохранения настроек пользователя не реагирует на клики

### Как воспроизвести.

Выбрать английский язык для панели менеджера в системных настройках
Перейти на страницу редактирования любого пользователя

### Версия EvoCMS

3.3.x

### Другая информация

Ошибка синтаксиса javascript в консоли браузера.

Причина: неэкранированный вывод текстовой строки. Если в строке присутствует апостроф (часто бывает в английских строках), то возникает ошибка.

Решение: либо отредактировать языковые строки unblock_message и block_message
Либо сделать экранирование.

**Comment by Pathologic** [comment]
Я что-то не понимаю, как воспроизвести.

**Comment by delphinpro** [comment]
Установить версию 3.3.1 (другие версии не проверял, но вероятно и в них воспроизводится, если там тот же принцип вывод строк)
Выбрать английский язык в панели управления
![20240124-170039](https://github.com/evocms-community/evolution/assets/1081988/16475740-236c-42e4-87bc-e62823700ef7)
Перейти на страницу редактирования пользователя /manager/#?a=88&id=1
Сохранение невозможно, кнопка не работает
В консоли ошибка
![20240124-170306](https://github.com/evocms-community/evolution/assets/1081988/25e400b5-42f2-4f0d-bc27-1d9078dfa036)
Синтаксическая ошибка приводит к прекращению дальнейшего выполнения js кода. Переменная actions не заполняется. Последующие клики приводят к ошибке
```
index.php?a=88&id=1:217 Uncaught TypeError: Cannot read properties of undefined (reading 'save')
    at HTMLAnchorElement.onclick (index.php?a=88&id=1:217:115)
```

Если посмотреть исходный код страницы, то видна причина в строке:

```javascript
blocked.innerHTML = '<b>This User will not be blocked after saving the User's data.</b>'
```

**Comment by helgispbru** [comment]
Это именно в 3.3.х такое, я тоже про это писал где-то. Может в чате, а не тут.
