### ISSUE TITLE
[Bug] EVO 3.1 Extras Module does not install templates

### ISSUE THREAD

**Issue by Nicola1971** [evocms-community/evolution#381]
### Summary

I'm used to creating packages containing custom templates, chunks, plugins and snippets to install with the Extras module.
With EVO 3.1, if the package contains templates .tpl, the installation fails and nothing is installed.
If I remove the template tpls from the package, the installation completes successfully.
If the package contains only templates, fails.

I found this error in the logs:
« Evolution CMS Parse Error »
Call to a member function count() on null
File .../assets/modules/store/installer/instprocessor-fast.php
Line 139

https://github.com/evocms-community/evolution/blob/3.1.x/assets/modules/store/installer/instprocessor-fast.php#L139

### EvoCMS version

3.1.24

### PHP version

7.4 and 8.1

**Comment by Pathologic** [comment]
Please, check.

**Comment by Nicola1971** [comment]
Thanks @Pathologic. now the templates are installed, but there is no TVs template assignments (all tvs are in red)

**Comment by Pathologic** [comment]
Can you provide a package with templates and tvs to test?

**Comment by Nicola1971** [comment]
This is the old 1.4x EVO-startup---Bootstrap Template with an Image TV assigned to the template.
Tested on 1.4x:  tv is assigned
Tested on latest 3.1 : tv is not assigned

[EVO-startup---Bootstrap-main.zip](https://github.com/evocms-community/evolution/files/14192775/EVO-startup---Bootstrap-main.zip)

**Comment by Nicola1971** [comment]
Another issue:
I've updated the package (just changed description to both template and tv) and changed "overwrite" from false to true.
it doesn't overwrite/update anything :(

Error in log:

Error encoding model [EvolutionCMS\Models\SiteTemplate] with ID [8] to JSON: Recursion detected

File	core/vendor/illuminate/database/Eloquent/JsonEncodingException.php
Line	18

The updated package:
[EVO-startup---Bootstrap-overwrite.zip](https://github.com/evocms-community/evolution/files/14193051/EVO-startup---Bootstrap-overwrite.zip)

Tested with 1.4x: works

**Comment by Pathologic** [comment]
Try again with new fixes.

**Comment by Nicola1971** [comment]
With latest fixes the tv is correctly assigned to the template :thumbsup:, but if you try to install the package a second time (overwite/update), nothing is installed.

`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '38-10' for key 'PRIMARY' (SQL: insert into `fzl6_site_tmplvar_templates` (`tmplvarid`, `templateid`) values (38, 10))`

Error information	
File	/home/devsite/public_html/core/vendor/illuminate/database/Connection.php
Line	712

**Comment by Pathologic** [comment]
Check.

**Comment by Nicola1971** [comment]
👍Solved the overwite/update issue. Thank you :)
