### ISSUE TITLE
[Bug] EVO 3.1 - CodeMirror is not defined

### ISSUE THREAD

**Issue by Nicola1971** [evocms-community/evolution#384]
### Summary

CodeMirror does not show when editing elements

Js errors in console
![Screenshot 2024-02-08 164541](https://github.com/evocms-community/evolution/assets/7342798/b77253c4-9c4e-43a0-957a-a8cb1ee44d62)

### EvoCMS version

3.1.24/3.1.25

### PHP version

8.1

**Comment by Pathologic** [comment]
https://github.com/evocms-community/evolution/archive/refs/tags/3.1.25.zip - take codemirror files here, I've updated the release.

**Comment by Nicola1971** [comment]
@Pathologic Tested with 3.1.2.5 from releases page (2 evo installations: local wamp and live server)

**Comment by Pathologic** [comment]
Just reinstall.
