### ISSUE TITLE
[Bug(?)] "Визуальный компонент" похоже, что не работает в blade

### ISSUE THREAD

**Issue by sashabeep** [evocms-community/evolution#390]
### Описание

Вывод тв-поля с визуальным компонентом в шаблонах blade возможен только через
```@evoParser('[*tv_name*]')```

### Как воспроизвести.

Задать визуальный компонент любому тв-параметру и вывести через ```{{$documentObject['tv_name']}}```

### Наблюдаемое поведение

Значение параметра выводится без учета визуального компонента

### Ожидаемое поведение

Возможно, как-то передавать переключатель на выводе?

### Версия EvoCMS

Evolution CE 3.1.27

**Comment by Pathologic** [comment]
Если с контроллерами, то можно так:
```
$this->addViewData(['mytv' => call_user_func_array('getTVDisplayFormat', evo()->documentObject['mytv'])]);
```

Или [создать свою директиву](https://community.evocms.ru/blog/docs/sobstvennye-direktivy-dlya-blejda.html):
```
//@display('mytv')
Blade::directive('display', function($params) {
    return "<?php echo isset(evo()->documentObject[{$params}]) && is_array(evo()->documentObject[{$params}]) ? call_user_func_array('getTVDisplayFormat', evo()->documentObject[{$params}]) : ''; ?>";
});
```
