### ISSUE TITLE
TinyMCE 4 settings don't work

### ISSUE THREAD

**Issue by fourroses666** [evocms-community/evolution#393]
### Summary

Using these settings don't work. No < br > but always < p > 
(Also tested with full theme and skin and manager default theme.)

![1](https://github.com/evocms-community/evolution/assets/523389/3265f9e0-0183-48af-876d-abefc473a2f5)
![2](https://github.com/evocms-community/evolution/assets/523389/54bce926-3106-432e-a15a-64499b66ed67)

### EvoCMS version

3.1.27

### PHP version

8.2

**Comment by XTRO123** [comment]
I cannot confirm this behavior for the specified versions and settings. The editor is working correctly.
![image](https://github.com/evocms-community/evolution/assets/2737316/383ac475-8b29-4196-96fe-88501f110f12)

**Comment by fourroses666** [comment]
Weird, I have to do a clean install and see. Maybe its because of some customization.

#EDIT: clean install doesn't have the issue.

Thanks for checking.
