### ISSUE TITLE
[Bug] Member has protected visibility

### ISSUE THREAD

**Issue by XTRO123** [evocms-community/evolution#396]
### Описание

рефлексию имеем для \DocumentParser, а в 
https://github.com/evocms-community/evolution/blob/64f6e83371706f8522cdcec2fa4a55aa88d6f62f/core/src/Core.php#L4395
метод protected https://github.com/AgelxNash/DocLister/blob/7f3309b1d952cf88e8ac50794c5fa9d36588d85d/assets/snippets/DocLister/lib/DLTemplate.class.php#L332

### Версия EvoCMS

3.1

### Версия Apache/nginx

2.4.56

### Версия PHP

8.2

### Версия MySQL

8

**Comment by Pathologic** [comment]
app('DLTemplate') использует другой класс, core/src/Parser.php.
