### ISSUE TITLE
[Bug] adding TV doesn't show in Elements in Tree

### ISSUE THREAD

**Issue by fourroses666** [evocms-community/evolution#398]
### Summary

When adding a TV doesn't show it in the list.
Only after saving Configuration page.
Don't know if its a ElementsInTree thing or EVO. 
Templates, Plugins and Snippets does work like expected.

![tv](https://github.com/evocms-community/evolution/assets/523389/73ac7d9a-17be-4284-b054-02dd1e8f93eb)

### EvoCMS version

3.1.27

### PHP version

8.2

**Comment by fourroses666** [comment]
I think only when there is no TV yet in the list.

**Comment by Pathologic** [comment]
It's ElementsInTree bug

**Comment by fourroses666** [comment]
https://github.com/extras-evolution/ElementsInTree/issues/6
