### ISSUE TITLE
Remove session ID cookie (at default)

### ISSUE THREAD

**Issue by fourroses666** [evocms-community/evolution#460]
When visiting an EVO website there is an "evoxxxx" cookie stored.
Even when its not needed to store the session-id.

Can is be removed from the system? 
Some clients have very strict policy.

**Comment by fourroses666** [comment]
Can't logout the manager. Can we set a sessioncookie when visiting /manager ?

**Comment by Pathologic** [comment]
https://github.com/evocms-community/UserManager/commit/8c566984286c799066b3fe7bbc1cee7dedcfc5ca

**Comment by fourroses666** [comment]
Would it be possible to have the option in Configuration to use session cookie or not. 
A radio button; Session cookie: Yes / No

**Comment by Pathologic** [comment]
No, session is started before everything.

**Comment by fourroses666** [comment]
_If I'm correct_ as soon as you browse the website you get a session cookie. Only when you add some php file manually it doesn't add the session cookie anymore.
