### ISSUE TITLE
После установки в настройках редактора текста слетает редактор кода у сущностей MODx [Bug] 

### ISSUE THREAD

**Issue by brutalhost** [evocms-community/evolution#467]
### Описание

Редактор кода стал обычным textarea после выставления TinyMCE 4 как редактора умолчанию. Аналогично если подключаю самописный плагин с использованием OnRichTextEditorRegister и OnRichTextEditorInit 

### Как воспроизвести.

1. Установка редактора текста
2. Конфигурация -> редактор текста по умолчанию
3. Открыть любую сущность с редактором кода: плагин, чанк, сниппет и т.д.
4. Вместо редактора кода будет стандартный textarea

### Наблюдаемое поведение

Если редактор текста выставлен по умолчанию - стандартные стили редактор кода подгружаются

### Ожидаемое поведение

Подгрузка стилей редактора кода

### Версия EvoCMS

3.3

**Comment by Pathologic** [comment]
Не получается воспроизвести.

**Comment by Pathologic** [comment]
@brutalhost
