### ISSUE TITLE
После установки 1.4.35 Fatal error в manager [Bug] 

### ISSUE THREAD

**Issue by dzh0n** [evocms-community/evolution#468]
### Описание

После установки в /manager/ выдает ошибку. 
Fatal error: Uncaught TypeError: Argument 1 passed to DocumentParser::setLocale() must be of the type string, null given, called in /manager/includes/document.parser.class.inc.php on line 527 and defined in /manager/includes/document.parser.class.inc.php:7072 Stack trace: #0 /manager/includes/document.parser.class.inc.php(527): DocumentParser->setLocale(NULL) #1 /manager/index.php(161): DocumentParser->getSettings() #2 {main} thrown in /manager/includes/document.parser.class.inc.php on line 7072

### Версия EvoCMS

1.4.35

### Версия PHP

7.4

**Comment by Pathologic** [comment]
Добавь в таблицу system_settings строку:
![image](https://github.com/user-attachments/assets/0d2c2b0b-965e-4319-8d7b-eead1fe4380c)
