### ISSUE TITLE
[Bug 3.3] Флэш сообщения не удаляются из сессии при обращении к ним

### ISSUE THREAD

**Issue by brutalhost** [evocms-community/evolution#470]
### Описание

В модуле scraper использую session()->flash('status', 'Данные успешно сохранены!'), подобного рода сообщения не удаляются после отображения, остаются висеть после перезагрузки.

### Как воспроизвести.

Характерно как для админки, так и для сайта:
```
@php
    session()->flash('status', 'Данные успешно сохранены!');
@endphp
@if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
@endif
```
После отображения содержимого @if просто закомментить session()->flash() - после повторной загрузки сообщение никуда не исчезнет

### Ожидаемое поведение

После обращения к флэш сообщению оно должно удалиться из сессии

### Версия EvoCMS

3.3

**Comment by brutalhost** [comment]
На фронте в 3.1.28 та же проблема, ```session()->flush();``` ```session()->forget('evocms-success');``` не удаляют из сессии

**Comment by brutalhost** [comment]
Та же проблема на 3.1, не срабатывают команды ```session()->forget('key)``` ```session()->flush();``` - это проверял на фронте. Ими хотел убрать flash сообщения вручную. В массиве ```$_SESSION``` они отсутствуют, есть только в ```session()->all();```.

**Comment by Pathologic** [comment]
В 3.1 session() не работает вообще.
