### ISSUE TITLE
[Bug 3.3] Tracy ломает вызов сниппета commerce

### ISSUE THREAD

**Issue by brutalhost** [evocms-community/evolution#476]
### Описание

При включении tracy ломается вывод сниппета commerce, ошибка `Undefined array key "modx_charset"`

### Как воспроизвести.

1. 
```php
// core/custom/config/tracy/active.php
<?php

return 'adminfrontonly';
//return false;
```
2. В blade:
```php
{!! evo()->runSnippet('Cart', ['theme' => 'mini']) !!}
```

### Наблюдаемое поведение

Выводится ошибка

### Ожидаемое поведение

Отработка сниппета как положено

### Версия EvoCMS

4.3

**Comment by Pathologic** [comment]
Где ошибка?

**Comment by brutalhost** [comment]
> Где ошибка?

На морде сайта

**Comment by Pathologic** [comment]
Полный вывод покажи. Потому что тут не в tracy проблема.

**Comment by brutalhost** [comment]
> Полный вывод покажи. Потому что тут не в tracy проблема.

https://disk.yandex.ru/d/hbKFq030ZkwFuA
