### ISSUE TITLE
[Bug] Unable to update or register user

### ISSUE THREAD

**Issue by koruku** [evocms-community/evolution#478]
### Summary

Unable to update user information or create users on the screen
 management screen > Permission management > User management.
I've been able to update articles and modules, so I think it's something related to users.

Also, in Evolution CE 1.4.34, Evolution CE 1.4.35, and Evolution CE 1.4.18 
manager/processors/save_user.processor.php
The code was the same.

### EvoCMS version

1.4.34

### PHP version

8.3.6

### MySQL version

8.0.39-0

### Any relevant information

ubuntu0.24.04.1

**Comment by Pathologic** [comment]
I cannot reproduce this issue in 1.4.35.
