### ISSUE TITLE
Рефактор управления правами

### ISSUE THREAD

**Issue by Pathologic** [evocms-community/evolution#50]
### Описание
Для групп пользователей и групп документов нужны отдельные страницы.

### Зачем это нужно?
Если пользователей или документов будет много, то управлять группами будет невозможно.

### Предлагаемое решение
Пользователи/документы на странице группы должны выводиться таблицей.

**Comment by autogen-travel** [comment]
Я похоже неправильно понял проблему. Сделал таблицы, открывающиеся по кнопке "Список".
А надо на отдельной вкладке чтобы была таблица? С возможностью добавления/удаления пользователя/ресурса?
С удалением вопросов нет, а как лучше сделать добавление? В смысле сам UI добавления.

**Comment by autogen-travel** [comment]
![addTables](https://github.com/evocms-community/evolution/assets/13348823/87a4453b-0caf-4a24-98b2-860c284c20d1)

**Comment by Pathologic** [comment]
Надо чтобы была таблица с пагинацией, потому что если в группе будет тысяча пользователей, то пользоваться этим всем будет невозможно. Про добавление/удаление не думал, в принципе можно было бы и удалять, используя эту таблицу, но тогда к ней не помешает и поиск приделать.
