### ISSUE TITLE
[BUG] Updating to v3.1.11 via CLI error

### ISSUE THREAD

**Issue by BBloke** [evocms-community/evolution#59]
### Summary 
Error during updating of site

### Step to reproduce
Ran php artisan make:site update

### Expected behavior
Updating should have completed without error

### Environment
EvoCMS version: v3.1.11 Evo CE upgrading from v3.1.9 Evo
Apache/nginx version:  2.4.53 Apache
PHP version:  7.4.29
MySQL version: MariaDB 10.6
Any relevant information:
Ran php artisan make:site update and got the following error.

20:    interface LoggerInterface
21:    {
22:        /**
23:         * System is unusable.
24:         *
25:         * @param string|\Stringable $message
26:         * @param mixed[] $context
27:         *
28:         * @return void
29:         */
30:        public function emergency(string|\Stringable $message, array $context = []);
31:
32:        /**
33:         * Action must be taken immediately.
34:         *

ParseError: syntax error, unexpected '|', expecting variable (T_VARIABLE) in \core\vend
r\psr\log\src\LoggerInterface.php:30
Stack trace:
#0 \core\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('D:\\Data\
a...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Psr\\Log\\LoggerI...')
#2 \core\vendor\composer\composer\src\Composer\IO\IOInterface.php(23): spl_autoload_cal
('Psr\\Log\\LoggerI...')
#3 \core\vendor\composer\ClassLoader.php(571): include('D:\\Data\\a...')
#4 \core\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('D:\\Data\
a...')
#5 [internal function]: Composer\Autoload\ClassLoader->loadClass('Composer\\IO\\IOI...')
#6 \core\vendor\composer\composer\src\Composer\IO\BaseIO.php(20): spl_autoload_call('Co
poser\\IO\\IOI...')
#7 \core\vendor\composer\ClassLoader.php(571): include('D:\\Data\\a...')
#8 \core\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('D:\\Data\
a...')
#9 [internal function]: Composer\Autoload\ClassLoader->loadClass('Composer\\IO\\Bas...')
#10 \core\vendor\composer\composer\src\Composer\IO\NullIO.php(20): spl_autoload_call('C
mposer\\IO\\Bas...')
#11 \core\vendor\composer\ClassLoader.php(571): include('D:\\Data\\a...')
#12 \core\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('D:\\Data
\a...')
#13 [internal function]: Composer\Autoload\ClassLoader->loadClass('Composer\\IO\\Nul...')
#14 \core\vendor\composer\composer\src\Composer\Console\Application.php(117): spl_autol
ad_call('Composer\\IO\\Nul...')
#15 \core\src\Console\SiteUpdateCommand.php(146): Composer\Console\Application->__const
uct()
#16 \core\src\Console\SiteUpdateCommand.php(44): EvolutionCMS\Console\SiteUpdateCommand
>startUpdate()
#17 \core\vendor\illuminate\container\BoundMethod.php(36): EvolutionCMS\Console\SiteUpd
teCommand->handle()
#18 \core\vendor\illuminate\container\Util.php(40): Illuminate\Container\BoundMethod::I
luminate\Container\{closure}()
#19 \core\vendor\illuminate\container\BoundMethod.php(93): Illuminate\Container\Util::u
wrapIfClosure(Object(Closure))
#20 \core\vendor\illuminate\container\BoundMethod.php(37): Illuminate\Container\BoundMe
hod::callBoundMethod(Object(DocumentParser), Array, Object(Closure))
#21 \core\vendor\illuminate\container\Container.php(653): Illuminate\Container\BoundMet
od::call(Object(DocumentParser), Array, Array, NULL)
#22 \core\vendor\illuminate\console\Command.php(136): Illuminate\Container\Container->c
ll(Array)
#23 \core\vendor\symfony\console\Command\Command.php(298): Illuminate\Console\Command->
xecute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#24 \core\vendor\illuminate\console\Command.php(121): Symfony\Component\Console\Command
Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#25 \core\vendor\symfony\console\Application.php(1015): Illuminate\Console\Command->run
Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 \core\vendor\symfony\console\Application.php(299): Symfony\Component\Console\Applic
tion->doRunCommand(Object(EvolutionCMS\Console\SiteUpdateCommand), Object(Symfony\Component\Console\Input\ArgvInput), O
ject(Symfony\Component\Console\Output\ConsoleOutput))
#27 \core\vendor\symfony\console\Application.php(171): Symfony\Component\Console\Applic
tion->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 \core\vendor\illuminate\console\Application.php(94): Symfony\Component\Console\Appl
cation->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 \core\artisan(37): Illuminate\Console\Application->run(Object(Symfony\Component\Con
ole\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 {main}

(stored in \core\storage\\logs\exception--2022-05-09--14-22--faf525de2d.html)

Downloading and overwriting and running install worked as expected.

Maybe it's worth stating not to update from normal version to CE version via artisan command?

**Comment by Pathologic** [comment]
It seems that some components require php 8.1

**Comment by Pathologic** [comment]
Or make composer update first

**Comment by Pathologic** [comment]
I've tested with php 7.4.29:
* composer update
* php artisan make:site update
![image](https://user-images.githubusercontent.com/3012304/167423268-125ace8c-0162-420d-aedc-7feb9c9b7e23.png)

**Comment by BBloke** [comment]
That's nice to know.  Thanks @Pathologic
