### ISSUE TITLE
[3.1.x] Права доступа для запуска модулей

### ISSUE THREAD

**Issue by sashabeep** [evocms-community/evolution#61]
### Описание
Subj

### Зачем это нужно?
Для разделения возможностей редакторов сайта

### Предлагаемое решение
Как в ветке 1.4

**Comment by Pathologic** [comment]
А разве оно сейчас не работает?

**Comment by sashabeep** [comment]
@Pathologic Не получилось ограничить доступ к модулям. Редактор всё равно может запустить модуль, даже если он не в группе пользователей, к которой привязана группа ресурсов, в которой модуль. Ресурсы не видит, а модули запускает без вопросов

**Comment by Pathologic** [comment]
https://github.com/evocms-community/evolution/commit/6f0c13a2a495a33c9983066b4384bf4d480cdf09 - замени эти файлы и проверь.

**Comment by sashabeep** [comment]
@Pathologic Похоже, что работает
