### ISSUE TITLE
v3.1.11 DocManager does not work with new permission and docgroups [BUG]

### ISSUE THREAD

**Issue by BBloke** [evocms-community/evolution#68]
When trying to remove permissions from documents I get the following error using DocManager

« Evolution CMS Parse Error »
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'table.modx_webgroup_access' doesn't exist

**Comment by BBloke** [comment]
I forked and updated it if need be: https://github.com/BBloke/DocManager

**Comment by Pathologic** [comment]
https://github.com/extras-evolution/DocManager/pull/2 - merged, thanks.
