### ISSUE TITLE
v3.1.11 Changing manager theme

### ISSUE THREAD

**Issue by BBloke** [evocms-community/evolution#69]
I have tried 2 installations of v3.1.11 and the Manager Color Theme.

I cannot save a different setting from the Configuration page when changing the color scheme.
If I use the icon in the Elements tree I can cycle through each setting.
This creates a cookie for the theme number to retain the setting.
Removing the cookie returns the theme to default from configuration page.

**Comment by fourroses666** [comment]
Do you mean: [(show_picker)] ?

**Comment by BBloke** [comment]
Its the site settings.

The pic is of my current settings and theme.
![image](https://user-images.githubusercontent.com/24464015/169338204-ace6b0b2-0248-4ac8-b776-1ec3c577bdfc.png)

It's set to 'header and sidebar are dark' but the theme is light (because of the switch tool).

![image](https://user-images.githubusercontent.com/24464015/169338407-c9052202-5b04-4c35-adca-a561d368c163.png)

If I remove the cookie for the theme it reverts to the site settings: header and sidebar are dark and it looks crap!

![image](https://user-images.githubusercontent.com/24464015/169339051-0ca404ac-dd27-4654-bc6c-33e832f8e58c.png)

Don't know why!

So changing to any other theme setting in configuration does not affect the theme at all.

So I can change the setting to everything dark.  Click Save.  The page refreshes to the dashboard. No change is made and the settings show no change either.

{long pause}

What happens in the configuration page is getting back to the database but not translating through!

I think something else if afoot just can't get my finger on it!
