### ISSUE TITLE
[BUG] 3.1.11 – After upgrade always same site content on different private web pages when logged in

### ISSUE THREAD

**Issue by leonie12** [evocms-community/evolution#73]
### Summary 
After upgrading from console to CE 3.1.11 as described by Pathologic in forum after login the loggedin page and all subpages show the content of  content field of page [ 17 ] which is private web but mentioned nowhere in login configuration.
When logged in the private submenu is shown and the correct breadcrumbs of the subpages are shown, even their header images (stored in MultiTV), BUT not the content of those different private subpages but the content of [ 17 ] (which is the private web page with the lowest ID – if this is of interest).

### Step to reproduce
See above.

### Observed behavior
See above.

### Expected behavior
After login there should be shown the content of login redirect page [ 30 ] and then the contents of the chosen private subpages, not the content of page xy.

### Environment
EvoCMS version: CE 3.1.11
Apache/nginx version: 
PHP version: 8.1
MySQL version:  5.5.5-10.3.28-MariaDB
Any relevant information: 
Pathologic/MODxAPI and FormLister are installed in their newest versions.
With 3.1.10 login/logout for web users worked flawlessly. The login redirected to [ 30 ] and opened a submenu with restricted pages.

**Comment by Pathologic** [comment]
Send me manager login and password - m@xim.name

**Comment by Pathologic** [comment]
...and site url as well :smile_cat:
