### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by Pathologic** [evocms-community/evolution#79]
### Описание
Заменить в админке RSS. Было бы неплохо сделать выбор каналов при установке.

### Зачем это нужно?
RSS от evolution-cms/evolution не актуальны.

**Comment by bossloper** [comment]
Feeds are not parsed on the home page. It does not matter what rss feed I try to add in the system configuration, it fails:

```
[09-Jun-2022 09:26:09 Europe/London] Failed to create an instance of PHP's XML parser. http://www.php.net/manual/en/ref.xml.php
[09-Jun-2022 09:26:09 Europe/London] MagpieRSS: Failed to parse RSS file. (Failed to create an instance of PHP's XML parser. http://www.php.net/manual/en/ref.xml.php)
```

https://github.com/evocms-community/evolution/blob/1.4.x/manager/media/rss/rss_parse.inc#L111

**Comment by Pathologic** [comment]
1.4:
https://github.com/evocms-community/evolution/commit/bb8651a685d69d5ad7606b3b1fcc57609ccb2a4d
https://github.com/evocms-community/evolution/commit/2af3ad368e02b8ccaffae5bb629bb5e17b72bee4
3.x:
https://github.com/evocms-community/evolution/commit/fa60009f5438b0cbdbdf405e745f91695675757e
https://github.com/evocms-community/evolution/commit/ab56549bfbe828148474c51497806cb11e5c5365
