### ISSUE TITLE
[BUG] v3 plugins - blank configuration parameter breaks site

### ISSUE THREAD

**Issue by BBloke** [evocms-community/evolution#83]
If a plugin has a blank configuration parameter then PHP complains the variable isn't declared.

Best example are Dashboard Last Users https://github.com/Nicola1971/DashboardLastWebUsers

Configuration parameter: ThisRole, ThisUser, HeadBG, HeadColor, BodyBG, BodyColor are all blank by default.

Dashboard doesn't load because "ThisRole" or others are not declared.  Giving them a value fixes this.

Is there a correct way to have blank configuration parameters in plugins so sites don't break?

This is on a synology NAS running Apache 2.2 and PHP 8.0

**Comment by Pathologic** [comment]
That's not a bug, variables (or $modx->event->params keys) are not declared for empty parameters. 
There should be a check for variable existence in "Dashboard Last Users":
```
$ThisRole = $ThisRole ?? 'default value';
```
