### ISSUE TITLE
[BUG] [(site_unavailable_message)]

### ISSUE THREAD

**Issue by fourroses666** [evocms-community/evolution#86]
3.1.11 -> Configuration: [(site_unavailable_message)]

Content is: `global.site_unavailable_message` and after removing it and go back to the Configuration page its back again.

This was already an issue but now I see this `global.site_unavailable_message` instead of the default message "Website is offline"

**Comment by Pathologic** [comment]
https://github.com/evocms-community/evolution/commit/f3e2366834a6a47bf243f33e0b302445afb500e5
https://github.com/evocms-community/evolution/commit/02ed05626b524dc7e3d932a28b6a889b1302a097

**Comment by fourroses666** [comment]
Works !
