### ISSUE TITLE
[BUG] v1.4.18 FileSource displays an error in PHP8

### ISSUE THREAD

**Issue by BBloke** [evocms-community/evolution#91]
Filesource in base installation needs a little tweak.

Add in at line 75 after global $content

```php
        // to stop empty filesources from producing an error
        if ( !isset($content['file_binding']) ) $content['file_binding'] = '';
```

before

```php
        if(substr(trim($content[$vals]),0,$count) == $include.' MODX_BASE_PATH.\'assets/'.$elm_name.'/')
```
This prevents a plugin with no static file source from producing a warning.  

You can see the warning if you edit CodeMirror.

There is an error when editing a plugin with no Configuration.  This is displayed

```
TypeError: Cannot read properties of undefined (reading 'label') []
```

**Comment by Pathologic** [comment]
Please, provide the steps to reproduce all these errors.

**Comment by BBloke** [comment]
1. Edit CodeMirror Plugin displays this error at the bottom of the screen.
2. 
![image](https://user-images.githubusercontent.com/24464015/172158392-eaef5a20-6b62-4bce-96e5-f6e5f97adc97.png)

This displays as CodeMirror has not static file declared.

![image](https://user-images.githubusercontent.com/24464015/172158522-0c39630c-418b-4a53-b1bc-16791b5e8bb6.png)

**Comment by BBloke** [comment]
> Please, provide the steps to reproduce all these errors.

All added in.  Hope it helps.

**Comment by Pathologic** [comment]
I cannot reproduce even with maximum detection level.

**Comment by bossloper** [comment]
I see it in error_log now with with detection level set to all, on PHP 8.0.19 and php 8.1.6
Though for me is is line 122. https://github.com/evocms-community/evolution/blob/1.4.x/assets/plugins/filesource/plugin.filesource.php#L122

`PHP Warning: Undefined array key "file_binding" in /home/evophp8/public_html/assets/plugins/filesource/plugin.filesource.php on line 122`
